### ISSUE TITLE
Returning objects from JS methods

### ISSUE THREAD

**Issue by shyndman** [matt-curtis/MochaJSWebScriptingObject#1]
Hey Matt,

I'm wondering — do you have any experience returning objects from the Sketch environment? Everything I try ends up with an empty Object on the WebView side. Other object types are no problems (Number, String, Array). I'm at a loss.

**Comment by matt-curtis** [comment]
Take a look at the [`WebScripting` protocol](https://developer.apple.com/documentation/webkit/incorporating_scripts_legacy/webscripting). You'll find that only primitive types like Number, String, Array, etc. can be exported by default. If you want to export another type of object to a WebView you'll have to explicitly wrap it inside of another `MochaJSWebScriptingObject` that exposes an interface for that object to the WebView side:

````js
@import 'MochaJSWebScriptingObject.js'

//  Create a WebView

var webView = WebView.new();

//  Expose functions

var webScriptingObject = MochaJSWebScriptingObject({
	getApp: function(){
		var app = [NSApplication sharedApplication];

		return MochaJSWebScriptingObject({
			displayDialog: function(message, title){
				[app displayDialog:message withTitle:title];
			}
		});
	}
});

var windowScriptObject = webView.windowScriptObject();

windowScriptObject.setValue_forKey_(webScriptingObject, "exported");
windowScriptObject.evaluateWebScript_("exported.getApp().displayDialog('hello!', 'wassuuup');");
````

**Comment by shyndman** [comment]
Works like a charm. Thanks Matt.
